-- Agregar columna codigo_dane a la tabla ciudades y poblar con códigos DIVIPOLA
ALTER TABLE ciudades ADD COLUMN IF NOT EXISTS codigo_dane VARCHAR(20);

-- Actualizar códigos DANE principales
UPDATE ciudades SET codigo_dane = '91001' WHERE LOWER(nombre) = 'leticia';
UPDATE ciudades SET codigo_dane = '91541' WHERE LOWER(nombre) = 'puerto nariño';
UPDATE ciudades SET codigo_dane = '05001' WHERE LOWER(nombre) IN ('medellín', 'medellin');
UPDATE ciudades SET codigo_dane = '05088' WHERE LOWER(nombre) = 'bello';
UPDATE ciudades SET codigo_dane = '05360' WHERE LOWER(nombre) IN ('itagüí', 'itagui');
UPDATE ciudades SET codigo_dane = '05266' WHERE LOWER(nombre) = 'envigado';
UPDATE ciudades SET codigo_dane = '05615' WHERE LOWER(nombre) = 'rionegro';
UPDATE ciudades SET codigo_dane = '05045' WHERE LOWER(nombre) = 'apartadó';
UPDATE ciudades SET codigo_dane = '05837' WHERE LOWER(nombre) = 'turbo';
UPDATE ciudades SET codigo_dane = '05631' WHERE LOWER(nombre) = 'sabaneta';
UPDATE ciudades SET codigo_dane = '81001' WHERE LOWER(nombre) = 'arauca';
UPDATE ciudades SET codigo_dane = '81736' WHERE LOWER(nombre) = 'saravena';
UPDATE ciudades SET codigo_dane = '81794' WHERE LOWER(nombre) = 'tame';
UPDATE ciudades SET codigo_dane = '81065' WHERE LOWER(nombre) = 'arauquita';
UPDATE ciudades SET codigo_dane = '08001' WHERE LOWER(nombre) = 'barranquilla';
UPDATE ciudades SET codigo_dane = '08758' WHERE LOWER(nombre) = 'soledad';
UPDATE ciudades SET codigo_dane = '08433' WHERE LOWER(nombre) = 'malambo';
UPDATE ciudades SET codigo_dane = '08573' WHERE LOWER(nombre) = 'puerto colombia';
UPDATE ciudades SET codigo_dane = '08685' WHERE LOWER(nombre) = 'sabanalarga';
UPDATE ciudades SET codigo_dane = '13001' WHERE LOWER(nombre) IN ('cartagena de indias', 'cartagena');
UPDATE ciudades SET codigo_dane = '13430' WHERE LOWER(nombre) = 'magangué';
UPDATE ciudades SET codigo_dane = '13838' WHERE LOWER(nombre) = 'turbaco';
UPDATE ciudades SET codigo_dane = '13052' WHERE LOWER(nombre) = 'arjona';
UPDATE ciudades SET codigo_dane = '13244' WHERE LOWER(nombre) = 'el carmen de bolívar';
UPDATE ciudades SET codigo_dane = '15001' WHERE LOWER(nombre) = 'tunja';
UPDATE ciudades SET codigo_dane = '15238' WHERE LOWER(nombre) = 'duitama';
UPDATE ciudades SET codigo_dane = '15759' WHERE LOWER(nombre) = 'sogamoso';
UPDATE ciudades SET codigo_dane = '15176' WHERE LOWER(nombre) = 'chiquinquirá';
UPDATE ciudades SET codigo_dane = '15572' WHERE LOWER(nombre) = 'puerto boyacá';
UPDATE ciudades SET codigo_dane = '17001' WHERE LOWER(nombre) = 'manizales';
UPDATE ciudades SET codigo_dane = '17380' WHERE LOWER(nombre) = 'la dorada';
UPDATE ciudades SET codigo_dane = '17174' WHERE LOWER(nombre) = 'chinchiná';
UPDATE ciudades SET codigo_dane = '17873' WHERE LOWER(nombre) = 'villamaría';
UPDATE ciudades SET codigo_dane = '17614' WHERE LOWER(nombre) = 'riosucio';
UPDATE ciudades SET codigo_dane = '18001' WHERE LOWER(nombre) = 'florencia';
UPDATE ciudades SET codigo_dane = '18753' WHERE LOWER(nombre) = 'san vicente del caguán';
UPDATE ciudades SET codigo_dane = '18592' WHERE LOWER(nombre) = 'puerto rico';
UPDATE ciudades SET codigo_dane = '85001' WHERE LOWER(nombre) = 'yopal';
UPDATE ciudades SET codigo_dane = '85010' WHERE LOWER(nombre) = 'aguazul';
UPDATE ciudades SET codigo_dane = '85440' WHERE LOWER(nombre) = 'villanueva';
UPDATE ciudades SET codigo_dane = '85263' WHERE LOWER(nombre) = 'pore';
UPDATE ciudades SET codigo_dane = '19001' WHERE LOWER(nombre) = 'popayán';
UPDATE ciudades SET codigo_dane = '19693' WHERE LOWER(nombre) = 'santander de quilichao';
UPDATE ciudades SET codigo_dane = '19573' WHERE LOWER(nombre) = 'puerto tejada';
UPDATE ciudades SET codigo_dane = '19532' WHERE LOWER(nombre) = 'patía';
UPDATE ciudades SET codigo_dane = '20001' WHERE LOWER(nombre) = 'valledupar';
UPDATE ciudades SET codigo_dane = '20011' WHERE LOWER(nombre) = 'aguachica';
UPDATE ciudades SET codigo_dane = '20228' WHERE LOWER(nombre) = 'codazzi';
UPDATE ciudades SET codigo_dane = '20045' WHERE LOWER(nombre) = 'bosconia';
UPDATE ciudades SET codigo_dane = '27001' WHERE LOWER(nombre) IN ('quibdó', 'quibdo');
UPDATE ciudades SET codigo_dane = '27361' WHERE LOWER(nombre) = 'istmina';
UPDATE ciudades SET codigo_dane = '27787' WHERE LOWER(nombre) = 'tadó';
UPDATE ciudades SET codigo_dane = '27006' WHERE LOWER(nombre) = 'acandí';
UPDATE ciudades SET codigo_dane = '23001' WHERE LOWER(nombre) = 'montería';
UPDATE ciudades SET codigo_dane = '23189' WHERE LOWER(nombre) = 'cereté';
UPDATE ciudades SET codigo_dane = '23660' WHERE LOWER(nombre) = 'sahagún';
UPDATE ciudades SET codigo_dane = '23417' WHERE LOWER(nombre) = 'lorica';
UPDATE ciudades SET codigo_dane = '23466' WHERE LOWER(nombre) = 'montelíbano';
UPDATE ciudades SET codigo_dane = '11001' WHERE LOWER(nombre) IN ('bogotá d.c.', 'bogota', 'bogotá');
UPDATE ciudades SET codigo_dane = '25754' WHERE LOWER(nombre) = 'soacha';
UPDATE ciudades SET codigo_dane = '25290' WHERE LOWER(nombre) = 'fusagasugá';
UPDATE ciudades SET codigo_dane = '25269' WHERE LOWER(nombre) = 'facatativá';
UPDATE ciudades SET codigo_dane = '25175' WHERE LOWER(nombre) = 'chía';
UPDATE ciudades SET codigo_dane = '25899' WHERE LOWER(nombre) = 'zipaquirá';
UPDATE ciudades SET codigo_dane = '25307' WHERE LOWER(nombre) = 'girardot';
UPDATE ciudades SET codigo_dane = '25473' WHERE LOWER(nombre) = 'mosquera';
UPDATE ciudades SET codigo_dane = '25430' WHERE LOWER(nombre) = 'madrid';
UPDATE ciudades SET codigo_dane = '94001' WHERE LOWER(nombre) IN ('puerto inírida', 'inírida');
UPDATE ciudades SET codigo_dane = '95001' WHERE LOWER(nombre) = 'san josé del guaviare';
UPDATE ciudades SET codigo_dane = '95015' WHERE LOWER(nombre) = 'calamar';
UPDATE ciudades SET codigo_dane = '41001' WHERE LOWER(nombre) = 'neiva';
UPDATE ciudades SET codigo_dane = '41551' WHERE LOWER(nombre) = 'pitalito';
UPDATE ciudades SET codigo_dane = '41298' WHERE LOWER(nombre) = 'garzón';
UPDATE ciudades SET codigo_dane = '41396' WHERE LOWER(nombre) = 'la plata';
UPDATE ciudades SET codigo_dane = '44001' WHERE LOWER(nombre) = 'riohacha';
UPDATE ciudades SET codigo_dane = '44430' WHERE LOWER(nombre) = 'maicao';
UPDATE ciudades SET codigo_dane = '44847' WHERE LOWER(nombre) = 'uribia';
UPDATE ciudades SET codigo_dane = '44279' WHERE LOWER(nombre) = 'fonseca';
UPDATE ciudades SET codigo_dane = '47001' WHERE LOWER(nombre) = 'santa marta';
UPDATE ciudades SET codigo_dane = '47189' WHERE LOWER(nombre) = 'ciénaga';
UPDATE ciudades SET codigo_dane = '47288' WHERE LOWER(nombre) = 'fundación';
UPDATE ciudades SET codigo_dane = '47245' WHERE LOWER(nombre) = 'el banco';
UPDATE ciudades SET codigo_dane = '50001' WHERE LOWER(nombre) = 'villavicencio';
UPDATE ciudades SET codigo_dane = '50006' WHERE LOWER(nombre) = 'acacías';
UPDATE ciudades SET codigo_dane = '50313' WHERE LOWER(nombre) = 'granada';
UPDATE ciudades SET codigo_dane = '50573' WHERE LOWER(nombre) = 'puerto lópez';
UPDATE ciudades SET codigo_dane = '52001' WHERE LOWER(nombre) = 'pasto';
UPDATE ciudades SET codigo_dane = '52835' WHERE LOWER(nombre) = 'tumaco';
UPDATE ciudades SET codigo_dane = '52356' WHERE LOWER(nombre) = 'ipiales';
UPDATE ciudades SET codigo_dane = '52838' WHERE LOWER(nombre) = 'túquerres';
UPDATE ciudades SET codigo_dane = '54001' WHERE LOWER(nombre) IN ('cúcuta', 'cucuta');
UPDATE ciudades SET codigo_dane = '54498' WHERE LOWER(nombre) = 'ocaña';
UPDATE ciudades SET codigo_dane = '54518' WHERE LOWER(nombre) = 'pamplona';
UPDATE ciudades SET codigo_dane = '54874' WHERE LOWER(nombre) = 'villa del rosario';
UPDATE ciudades SET codigo_dane = '54405' WHERE LOWER(nombre) = 'los patios';
UPDATE ciudades SET codigo_dane = '86001' WHERE LOWER(nombre) = 'mocoa';
UPDATE ciudades SET codigo_dane = '86568' WHERE LOWER(nombre) = 'puerto asís';
UPDATE ciudades SET codigo_dane = '86320' WHERE LOWER(nombre) = 'orito';
UPDATE ciudades SET codigo_dane = '63001' WHERE LOWER(nombre) = 'armenia';
UPDATE ciudades SET codigo_dane = '63130' WHERE LOWER(nombre) = 'calarcá';
UPDATE ciudades SET codigo_dane = '66001' WHERE LOWER(nombre) = 'pereira';
UPDATE ciudades SET codigo_dane = '66170' WHERE LOWER(nombre) = 'dosquebradas';
UPDATE ciudades SET codigo_dane = '66682' WHERE LOWER(nombre) = 'santa rosa de cabal';
UPDATE ciudades SET codigo_dane = '68001' WHERE LOWER(nombre) = 'bucaramanga';
UPDATE ciudades SET codigo_dane = '68276' WHERE LOWER(nombre) = 'floridablanca';
UPDATE ciudades SET codigo_dane = '68307' WHERE LOWER(nombre) = 'girón';
UPDATE ciudades SET codigo_dane = '68547' WHERE LOWER(nombre) = 'piedecuesta';
UPDATE ciudades SET codigo_dane = '68081' WHERE LOWER(nombre) = 'barrancabermeja';
UPDATE ciudades SET codigo_dane = '70001' WHERE LOWER(nombre) = 'sincelejo';
UPDATE ciudades SET codigo_dane = '70215' WHERE LOWER(nombre) = 'corozal';
UPDATE ciudades SET codigo_dane = '70708' WHERE LOWER(nombre) = 'san marcos';
UPDATE ciudades SET codigo_dane = '70820' WHERE LOWER(nombre) = 'tolú';
UPDATE ciudades SET codigo_dane = '73001' WHERE LOWER(nombre) IN ('ibagué', 'ibague');
UPDATE ciudades SET codigo_dane = '73268' WHERE LOWER(nombre) = 'espinal';
UPDATE ciudades SET codigo_dane = '73443' WHERE LOWER(nombre) = 'melgar';
UPDATE ciudades SET codigo_dane = '73349' WHERE LOWER(nombre) = 'honda';
UPDATE ciudades SET codigo_dane = '76001' WHERE LOWER(nombre) = 'cali';
UPDATE ciudades SET codigo_dane = '76520' WHERE LOWER(nombre) = 'palmira';
UPDATE ciudades SET codigo_dane = '76109' WHERE LOWER(nombre) = 'buenaventura';
UPDATE ciudades SET codigo_dane = '76834' WHERE LOWER(nombre) = 'tuluá';
UPDATE ciudades SET codigo_dane = '76111' WHERE LOWER(nombre) = 'buga';
UPDATE ciudades SET codigo_dane = '76147' WHERE LOWER(nombre) = 'cartago';
UPDATE ciudades SET codigo_dane = '76364' WHERE LOWER(nombre) = 'jamundí';
UPDATE ciudades SET codigo_dane = '76892' WHERE LOWER(nombre) = 'yumbo';
UPDATE ciudades SET codigo_dane = '97001' WHERE LOWER(nombre) = 'mitú';
UPDATE ciudades SET codigo_dane = '99001' WHERE LOWER(nombre) = 'puerto carreño';
UPDATE ciudades SET codigo_dane = '88001' WHERE LOWER(nombre) = 'san andrés';

-- Fallback genérico para cualquier ciudad restante que no tenga DANE code
UPDATE ciudades SET codigo_dane = LPAD(id::text, 5, '0') WHERE codigo_dane IS NULL;
